
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwluonpgnqbnmtyidvyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bHVvbnBnbnFibm10eWlkdnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTM2MDMsImV4cCI6MjA2NDQyOTYwM30.kk0d4rImWJNJuX0zTgL-8ZChuLNaj3vnA3XlTYJ7RMc";

// Configure Supabase client with explicit auth settings for session persistence
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
